### ISSUE TITLE
I can't run the example

### ISSUE THREAD

**Issue by lukaszszyman** [buijs-dev/klutter-cookbook#1]
I downloaded klutter-cookbook source files. I wanted to run hello_world example.
I followed Readme.md to setup local.properties and run `./gradlew build -p "platform”` with the following exception:

```
FAILURE: Build failed with an exception.

* Where:
Build file ‘/klutter-cookbook-main/hello_world/android/build.gradle'

* What went wrong:
Could not compile build file '/klutter-cookbook-main/hello_world/android/build.gradle'.
> startup failed:
  General error during conversion: Unsupported class file major version 62
  
  java.lang.IllegalArgumentException: Unsupported class file major version 62
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:196)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:177)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:163)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:284)
        at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)
	…
```

After upgrading targetSdkVersion 33, compileSdkVersion 33 and gradle plugins - I have sync error. 
```
Gradle DSL method not found: 'android()'

Possible causes:

Your project may be using a version of the Android Gradle plug-in that does not contain the method (e.g. 'testCompile' was added in 1.1.0). ```  and `./gradlew build -p "platform”` still returns the same exception. 

Can you advice what I did wrong?

**Comment by buijs-dev** [comment]
The error you're getting "Unsupported class file major version 62", means the Java version you are using is incompatible. Which Java version do you use? 

 Just run the following in your terminal:
```
java --version
```

Don't upgrade the android versions because they require a higher AGP (and others) as well. So please revert that.

**Comment by lukaszszyman** [comment]
java --version
```
openjdk 18.0.1.1 2022-04-22
OpenJDK Runtime Environment (build 18.0.1.1+2-6)
OpenJDK 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing)
```

I have Macbook M1 Pro chip ARM64.
Android Studio Iguana | 2023.2.1.

**Comment by buijs-dev** [comment]
Gradle 7.2 is incompatible with Java 18. See compatibility [matrix](https://docs.gradle.org/current/userguide/compatibility.html).

The solution is to install Java 16 or upgrade the Gradle version to 7.5 in the gradle.properties. If you do the latter, don't forget to bump it in the android directory as well (there are multiple grade wrappers).

**Comment by buijs-dev** [comment]
I've updated the cookbook example to 2023.3.1.beta which works with gradle 8.0. If you pull the main branch again then it should work with Java 18 on your machine. I'll leave this ticket open so let me know if that works for you.

**Comment by lukaszszyman** [comment]
Hello, now I have the following error, trying to run `./kradlew build` in the /hello_world project (./kradle/kradle-wrapper.jar and kradle.env added like in readme + run `flutter pub get`).
```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/hello_world/android/build.gradle' line: 5

* What went wrong:
A problem occurred evaluating project ':android'.
> Failed to apply plugin 'dev.buijs.klutter'.
   > Could not create plugin of type 'KlutterGradlePlugin'.
      > Could not generate a decorated class for type KlutterGradlePlugin.
         > com/google/devtools/ksp/gradle/KspExtension

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':android'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 892ms
Exception in thread "main" java.io.IOException: Failed to execute command: 

        at dev.buijs.klutter.kore.tasks.ExecutorKt.finish(Executor.kt:87)
        at dev.buijs.klutter.kradle.ExecGradleCommandKt.execGradleCommand(ExecGradleCommand.kt:45)
        at dev.buijs.klutter.kradle.ExecGradleCommandKt.execGradleCommand(ExecGradleCommand.kt:29)
        at dev.buijs.klutter.kradle.BuildKt.build(Build.kt:7)
        at dev.buijs.klutter.kradle.MainKt.main(Main.kt:50)
```

**Comment by buijs-dev** [comment]
Can you show your build file '/hello_world/android/build.gradle'? Make sure you don't have any local changes.

**Comment by lukaszszyman** [comment]
Exactly the same as https://github.com/buijs-dev/klutter-cookbook/blob/main/hello_world/android/build.gradle :(

So what I did:
1. Downloaded code zip file, unpacked it
2. Created hello_world/.kradle/kradle-wrapper.jar and hello_world/kradle.env as described here: https://github.com/buijs-dev/klutter-cookbook/tree/main?tab=readme-ov-file
3. Put hello_world/local.properties and hello_world/android/local.properties with the declaration of sdk.dir and flutter.sdk as described here: https://github.com/buijs-dev/klutter-cookbook/tree/main/hello_world
4. Run flutter pub get in hello_world/
5. Run ./kradlew build

**Comment by buijs-dev** [comment]
Thank you, I managed to reproduce the issue. 

The root cause is a missing dependency, which is resolved when I add mavenLocal as a repository... So there might be a discrepancy between the 2023.3.1.beta version I have in my local repository and the one that is uploaded to maven. I will see what I can do to fix it.

**Comment by buijs-dev** [comment]
@lukaszszyman thank you for your patience. It should work now. You'll have to do use 'Refresh Gradle dependencies' to get the updated 2023.3.1.beta plugin. There was an issue where the gradle plugin maven-publish would create a faulty pom file when uploading to maven, but not when uploading to maven local... I never noticed this because of the mavenLocal in the cookbook.

**Comment by lukaszszyman** [comment]
Unfortunatelly, I still have build/sync problems.
I downloaded source code once again from scratch and followed the same steps.

After `./kradlew build` in hello_world/ I have the following error:
```
* What went wrong:
Could not determine the dependencies of task ':klutter:hello_world:compileDebugKotlinAndroid'.
> No matching toolchains found for requested specification: {languageVersion=17, vendor=any, implementation=vendor-specific}.
   > No locally installed toolchains match (see https://docs.gradle.org/8.0/userguide/toolchains.html#sec:auto_detection) and toolchain download repositories have not been configured (see https://docs.gradle.org/8.0/userguide/toolchains.html#sub:download_repositories).
``` 

Additionally I had the following warning:
``` 
> Configure project :klutter:hello_world
w: Multiplatform/Android-V1-SourceSetLayout: Multiplatform/Android-V1-SourceSetLayout is deprecated. Use Multiplatform/Android-V2-SourceSetLayout instead. 
To enable Multiplatform/Android-V2-SourceSetLayout: put the following in your gradle.properties: 
kotlin.mpp.androidSourceSetLayoutVersion=2
```

When I try to sync hello_world/example/android in Android Studio, then 
```
Unresolved module dependency :klutter:hello_world (:) in :klutter:hello_world (BuildId(buildRoot=/klutter-cookbook/hello_world/example/android)). Neither the source set nor the artifact property was populated by the Android Gradle plugin.
java.lang.IllegalStateException: Unresolved module dependency :klutter:hello_world (:) in :klutter:hello_world (BuildId(buildRoot=/klutter-cookbook/hello_world/example/android)). Neither the source set nor the artifact property was populated by the Android Gradle plugin. 
```

**Comment by buijs-dev** [comment]
Can you add the following to the setting.gradle(.kts) files:

`plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.4.0'
}`

I'm curious if that fixes anything. 

Also try to install Java 17 on your machine instead of 18. I use sdkman to easily switch between SDK versions, if that helps...

The Android sourcesets lay-out warning can be ignored because it does not matter here (2024.1.1.beta uses the new DSL though). 

And the last error makes sense as well due to the Java toolchain. It should be gone when we fix the root cause.

**Comment by lukaszszyman** [comment]
Adding this to hello_world/settings.gradle.kts at the beggining of a file helped a bit:
```
plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.4.0"
}
```
--> Displayed errors about java 17/18.

Changing Java version to 17
```
openjdk 17.0.10 2024-01-16
OpenJDK Runtime Environment Homebrew (build 17.0.10+0)
OpenJDK 64-Bit Server VM Homebrew (build 17.0.10+0, mixed mode, sharing)
```
->
```
w: Interop library /.gradle/caches/modules-2/files-2.1/dev.buijs.klutter/flutter-engine-iosArm64/2023.1.1.beta/d7ea0b8d2a39cdbbc75b9fdbcb53b223111e8558/flutter-engine-kmp-cinterop-Flutter can't be exported with -Xexport-library
e: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld invocation reported errors
Please try to disable compiler caches and rerun the build. To disable compiler caches, add the following line to the gradle.properties file in the project's root directory:
    
    kotlin.native.cacheKind.iosArm64=none
    
Also, consider filing an issue with full Gradle log here: https://kotl.in/issue
The /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld command returned non-zero exit code: 1.
output:
-iphoneos_version_min has been renamed to -ios_version_min
ld: unknown options: -sdk_version 
```

I added  `kotlin.native.cacheKind.iosArm64=none` to the hello_world/gradle.properties, but other errors still exist.

Looks like it still looks for 2023.1.1.beta version

**Comment by buijs-dev** [comment]
Can you show the error?

**Comment by lukaszszyman** [comment]
```
> Task :klutter:hello_world:kspCommonMainKotlinMetadata
w: [ksp] Encountered SquintMessageSource without source files during [validateResponses]: []
w: [ksp] Encountered duplicate SquintMessageSource during [validateResponses]: []
w: [ksp] Encountered unknown Types during [validateResponses]: []
w: [ksp] Encountered CustomTypes without members during [validateResponses]: []

> Task :klutter:hello_world:linkDebugFrameworkIosArm64 FAILED
w: Interop library /.gradle/caches/modules-2/files-2.1/dev.buijs.klutter/flutter-engine-iosArm64/2023.1.1.beta/d7ea0b8d2a39cdbbc75b9fdbcb53b223111e8558/flutter-engine-kmp-cinterop-Flutter can't be exported with -Xexport-library
e: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld invocation reported errors

The /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld command returned non-zero exit code: 1.
output:
-iphoneos_version_min has been renamed to -ios_version_min
ld: unknown options: -sdk_version 

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':klutter:hello_world:linkDebugFrameworkIosArm64'.

...

Exception in thread "main" java.io.IOException: Failed to execute command: 

        at dev.buijs.klutter.kore.tasks.ExecutorKt.finish(Executor.kt:87)
        at dev.buijs.klutter.kradle.ExecGradleCommandKt.execGradleCommand(ExecGradleCommand.kt:45)
        at dev.buijs.klutter.kradle.ExecGradleCommandKt.execGradleCommand(ExecGradleCommand.kt:29)
        at dev.buijs.klutter.kradle.BuildKt.build(Build.kt:7)
        at dev.buijs.klutter.kradle.MainKt.main(Main.kt:50)
```

**Comment by buijs-dev** [comment]
So the good news is this is all iOS specific, so running on Android should work when we fix this. 
The flutter-engine 2023.1.1.beta is the latest version and compatible with 2023.3.1.beta Gradle plugin, so that is fine as well.
I'm unable to reproduce this so I am not sure what is going on.
What is your xcode version?

**Comment by lukaszszyman** [comment]
XCode Version 15.3 (15E204a)

These errors are after running `./kradlew build` on my Mac OS 14.4 (23E214), Chip Apple M1 Pro,

**Comment by buijs-dev** [comment]
Thanks! I can reproduce the issue with xcode 15.3. Will have to dig a little deeper to find what's wrong.

**Comment by buijs-dev** [comment]
This seems to be an issue with Kotlin Multiplatform, see [KT-60230](https://youtrack.jetbrains.com/issue/KT-60230).

I've verified this issue is fixed with Klutter 2024.1.1.beta, which uses Kotlin 1.9.10. I'm still working on that but it should be done in a month or so I think.

For now if you want to work with the recipes there's 2 things you could do:

1. Downgrade Xcode to 14 (then everything works as is).
2. Manually bump all Kotlin dependencies from 1.8.20 to 1.9.10 (just do a search and replace in the project for 1.8.20) and rename sourceset androidTest to androidUnitTest. 

You will get errors and warnings with the second option but it does work. I verified this on a M1 macbook with Xcode 15.3.

Let me know if you get it up and running.

**Comment by buijs-dev** [comment]
@lukaszszyman could you try the updated recipes and see if it works on your machine?

**Comment by lukaszszyman** [comment]
Hey. I tried the following steps

1. Clone git project
2. Run ‘flutter pub get’ in klutter-cookbook/hello_world
3. Run ‘./gradlew klutterGetKradle’ in klutter-cookbook/hello_world
4. Create kradle.env file in klutter-cookbook/hello_world (as in README.md)
5. Create local.proporties in klutter-cookbook/hello_world and klutter-cookbook/hello_world/android and klutter-cookbook/hello_world/example/android (as in README.md)
6. Run ‘./kradle build’ in klutter-cookbook/hello_world 
I had some errors:

```
> Task :klutter:hello_world:assemblePlatformReleaseXCFramework
xcframework successfully written out to: klutter-cookbook/hello_world/platform/build/XCFrameworks/release/Platform.xcframework
> Task :klutter:hello_world:klutterCopyFramework FAILED
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
```

and many similar errors saying  

```
e: /User/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-serialization-protobuf-jvm/1.6.3/c4be6e5ab24b5422a7b4642f69e4e3239fb59014/kotlinx-serialization-protobuf-jvm-1.6.3.jar!/META-INF/kotlinx-serialization-protobuf.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
```

7. However, I was able to run Android program from klutter-cookbook/hello_world/example/android

**Comment by buijs-dev** [comment]
Awesome thank you! The warnings are known and can just be ignored.
